# Generated by Django 4.2.30 on 2026-05-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Nombre del proyecto')),
                ('responsable', models.CharField(max_length=255, verbose_name='Responsable / Autor')),
                ('categoria', models.CharField(choices=[('documento', 'Documento'), ('imagen', 'Imagen'), ('captura_pantalla', 'Captura de pantalla'), ('informe', 'Informe'), ('presentacion', 'Presentación'), ('otro', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('url_archivo', models.URLField(verbose_name='URL pública del archivo')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre original del archivo')),
                ('tipo_archivo', models.CharField(max_length=100, verbose_name='Tipo de archivo (MIME)')),
                ('tamano_archivo', models.PositiveIntegerField(verbose_name='Tamaño del archivo (bytes)')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Evidencia de Proyecto',
                'verbose_name_plural': 'Evidencias de Proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
